name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: PR Linter
      uses: yogevbd/pr-lint-action@1.0.1
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Run tests
      uses: cclauss/GitHub-Action-for-pytest@0.0.2
      with:
        args: python -m pip install . && cd src && pytest
